# Generated by Django 4.2.3 on 2023-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume',
            options={},
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='contactoCelular',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='contactoEmail',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='precio',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='imagenPerfume',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
