# Generated by Django 4.2.3 on 2023-09-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0003_perfil_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='cuerpo',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='receptor',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='emisor',
            new_name='sender',
        ),
    ]
