# Generated by Django 4.2.3 on 2023-09-11 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0004_rename_cuerpo_mensaje_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='linkGithub',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='linkLinkedin',
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppBase.avatar'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
